package com.panteras.pack;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
 // This means URL's start with /demo (after Application path)
public class PanteraController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PanteraRepository panteraRepository;


    @RequestMapping(path="/home")
    public @ResponseBody Iterable<Pantera> getAllUsers() {
        // This returns a JSON or XML with the users
        return panteraRepository.findAll();
    }
}